name: ⭐ Feature request
description: Create a detailed feature request.
title: 'feat: <title>'
labels: [ feature-request ]
body:
  - type: dropdown
    attributes:
      label: Type
      options:
        - Functionality
        - Cosmetic
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Issue
      description: What is the current problem. Why does it require a feature request?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Feature
      description: Describe your feature in detail. How does it solve the issue?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: Why should your feature should be considered?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add additional context here.
    validations:
      required: false
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you haven't done these steps.
      options:
        - label: I have searched the existing issues and this is a new and no duplicate or related to another open issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: I filled out all of the requested information in this issue properly.
          required: true
        - label: The issue is related solely to the ReVanced Manager
          required: true
