name: Android Debug

on:
  push:
    branches: [ "compose", "dev" ]
  pull_request:
    branches: [ "compose", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Build with Gradle
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew assembleDebug
    - name: Store generated APK file
      uses: actions/upload-artifact@v2
      with:
        name: manager
        path: ./app/build/outputs/apk/debug/app-debug.apk
